spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema_db
    username: postgres
    password: "@@22@@22klkl"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        springdoc:
          api-docs:
            path: /api-docs
          swagger-ui:
            path: /swagger-ui.html
            operations-sorter: alpha
            tags-sorter: alpha